### ISSUE TITLE
[FEATURE] Ensure compatibility with Wagtail Model Translation

### ISSUE THREAD

**Issue by niccolomineo** [coderedcorp/coderedcms#224] opened 2019-08-01 00:13 UTC
**Is your feature request related to a problem? Please describe.**
When installing Wagtail Model Translation, the module does not work on CoderedCMS. Right before the migration step, an error is returned:

`python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 95, in _patch_page_models
    model.get_edit_handler.cache_clear()
AttributeError: 'function' object has no attribute 'cache_clear'`

**Describe the solution you'd like**
CoderedCMS should effortlessly support the Wagtail Model Translation module, as it is one of the most popular ways to go about dynamic content translation in Wagtail.

**Comment by vsalvino** [comment] 2019-08-01 17:08
Good find. Looking at how `wagtail_modeltranslation` expects `get_edit_handler` to be a property rather than a function, I'm wondering how this could be fixed. I'm pretty sure wagtail allows `get_edit_handler` to be a function, which is how we are using it. Might have to patch Wagtail model translation up stream to allow both.

This will require some more research and debugging. I would be happy to accept a pull request if you're able to figure out a solution.

**Comment by vsalvino** [comment] 2019-08-01 17:09
Linking to #57 for more internationalization discussion.

**Comment by niccolomineo** [comment] 2019-08-02 07:32
> Good find. Looking at how `wagtail_modeltranslation` expects `get_edit_handler` to be a property rather than a function, I'm wondering how this could be fixed. I'm pretty sure wagtail allows `get_edit_handler` to be a function, which is how we are using it. Might have to patch Wagtail model translation up stream to allow both.
> 
> This will require some more research and debugging. I would be happy to accept a pull request if you're able to figure out a solution.

I am wondering, since `wagtail-modeltranslation` is a wrapper for django-modeltranslation, if it wouldn't be better to make a `coderedcms-modeltranslation` package, as a fork of `wagtail-modeltranslation`.

**Comment by niccolomineo** [comment] 2019-08-02 16:44
The `cache_clear` error can be fixed by redecorating `get_edit_handler()` with `@cached_classmethod` (`coderedcms.models.page_models`, line 486).

At that point, fields such as the `body` field would not appear as translated on page creation / edit. I suspect that's because `CoderedPage` is `abstract`. To fix that, I just removed 

`content_panels = CoderedWebPage.content_panels + [
    StreamFieldPanel('body')
]`

from `page_models.CoderedWebPage` and placed it directly in `website/models.py`.

Would that be acceptable?

**Comment by vsalvino** [comment] 2019-08-02 17:28
Interesting. I think adding `@cached_classmethod` would be a good move.

Regarding the `content_panels`... I would not remove them from codered, but you could just add the line into your own `website/models.py`... correct?

Feel free to make a pull request, I will happily review and test it out.

**Comment by niccolomineo** [comment] 2019-08-03 07:09
> Regarding the `content_panels`... I would not remove them from codered, but you could just add the line into your own `website/models.py` to override and define it there explicitly... correct?

By leaving the untranslateable `content_panel` there (`page_models.py`, line 629), it would still appear on page creation / edit together with the custom "body" (translateable) panel. See below:

![coderedcms](https://user-images.githubusercontent.com/5409469/62408728-896c2580-b5cd-11e9-858d-b2186b312110.png)

**Comment by vsalvino** [comment] 2019-08-03 15:35
I see... That must be because `CoderedPage` is actually a concrete model (although I would still expect a website/models.py page should be able to override it).

I wonder if we changed `content_panels` to be a function instead, that then returned the panels, if that would work better?

**Comment by vsalvino** [comment] 2019-08-07 16:33
Fixed via #236 and #233

**Closed by vsalvino** 2019-08-07 16:33 UTC
Labels: enhancement

**Comment by ayushin** [comment] 2020-05-12 20:16
Is this supposed to be working now?

**Comment by vsalvino** [comment] 2020-05-12 21:14
If it is not, then re-open the issue with steps to reproduce :)

**Comment by ayushin** [comment] 2020-05-13 05:19
Ah, I was not sure if I missed something very simple so I did not want to bother you guys with this. But indeed, perhaps it would be in any case useful to document this for others.

When I try to add `wagtail-modeltranslation` to an existing project by adding this:

```
    'wagtail_modeltranslation',
    'wagtail_modeltranslation.makemigrations',
    'wagtail_modeltranslation.migrate',
```
and this

```
LANGUAGES = [
    ('en-us', _('English')),
    ('cs-cz', _('Czech'))
]
```

then when I try to register a model in `translation.py` like this:
```
from modeltranslation.decorators import register
from modeltranslation.translator import TranslationOptions

from .models import WebPage


@register(WebPage)
class WebPageTR(TranslationOptions):
    fields = (
        'body',
    )
```

I get;

`modeltranslation.translator.DescendantRegistered: Model "Page" cannot be registered after its subclass "CoderedPage"`

Do I miss something obvious?

**Comment by ayushin** [comment] 2020-05-13 05:22
OK, yes,  found the solution here a moment later;

https://github.com/infoportugal/wagtail-modeltranslation/issues/182

**Comment by ayushin** [comment] 2020-05-13 09:21
After playing with the order of `INSTALLED_APPS` still something is amiss:

The moment I add a responsive row to a page body, I am no longer able to access translated fields for that page, i.e. in my case `VIEW / EDIT FIELDS FOR CS-CZ EN-US` become greyed out and when I click on either the page just reloads.
