### ISSUE TITLE
CoderedPage.cover_image is not extensible or swappable

### ISSUE THREAD

**Issue by wamcvey** [coderedcorp/coderedcms#325] opened 2020-06-26 21:44 UTC
#### Describe the bug

Codrered defines a base `CoderedPage` model that include a `cover_image` field that builds a ForeignKey directly to `wagtailimages.Image` rather than indirecting to `settings.WAGTAILIMAGES_IMAGE_MODEL` via `wagtail.images.get_image_model()` or `wagtail.images.get_image_model_string()` (as documented at: 
https://docs.wagtail.io/en/v2.9/advanced_topics/images/custom_image_model.html)

Additionally, neither application developers or site administrators can override the `cover_image` behavior in 3rd party applications or even in the site's `website` models because although models like `website.models.WebPage` inherit from the abstract model `CoderedWebPage`, that class itself inherits from `CoderedPage` which is *not* abstract and is where the `cover_image` attribute is defined. As such, Django won't allow overriding the field definition (as documented at: https://docs.djangoproject.com/en/2.2/topics/db/models/#field-name-hiding-is-not-permitted).

#### Steps to reproduce
1. Define a new custom Wagtail Image  model per: https://docs.wagtail.io/en/v2.9/advanced_topics/images/custom_image_model.html
2. Migrate and configure that new class to be the default Image class for Wagtail.
3. Attempt to add a cover_image onto any Codered derived models

#### Expected behavior

I would expect that custom Image types would be supported by wagtail. Notably, if I define a new `WAGTAILIMAGES_IMAGE_MODEL`, I would expect that codered models would allow me to use that image model as a `cover_image` on my Codered derived pages. I would expect that there would need to be a migration if a change to an existing site were to occur, but after migrating to apply the new fields, I should be able to proceed

Additionally, I would expect that most fields in Codered objects should be defined on abstract classes that site administrators can tweak as they see fit within their `website` derived models. Having the massive number of attributes added to the `CoderedPage` with that model being non-abstract locks those field definitions for the entire class tree. In this case, I can't override `cover_image` with an implementation that uses the new image model because that attribute is a Field defined on a non-abstract class, so django won't let me override it.

#### Additional context

Slack thread related to the subject:
https://wagtailcms.slack.com/archives/CEU45SBRR/p1593206087138300?thread_ts=1593194915.135800&cid=CEU45SBRR

(in the #coderedcms channel)

**Comment by wamcvey** [comment] 2020-06-26 21:58
As a more complete step to reproduce, this is the custom Image I'm trying to move my site to use:
```
class ProvenancedImage(AbstractImage):
    """An extended Image class that tracks the provenance of the image
    """
    image_attribution = models.CharField(
        max_length=1024, blank=True,
        help_text="Who is the source of the image")
    image_attribution_url = models.URLField(
        max_length=1024, blank=True,
        help_text="URL to the origination of the image" )
    show_attribution = models.BooleanField(
        default=False,
        help_text="Source of the image requests the display of the attribution")
    license_notes = models.TextField(blank=True,
        help_text="Any extra info on image license (not to be displayed)")

    admin_form_fields = Image.admin_form_fields + (
        'image_attribution',
        'image_attribution_url',
        'show_attribution',
        'license_notes',
    )

class ProvenancedImageRendition(AbstractRendition):
    image = models.ForeignKey(ProvenancedImage,
                              on_delete=models.CASCADE,
                              related_name='renditions')

    class Meta:
        unique_together = ('image', 'filter_spec', 'focal_point_key')

```

If you drop that into `website/models.py` and in `settings.py` set: 
```
WAGTAILIMAGES_IMAGE_MODEL = 'website.ProvenancedImage'
``` 
Once you `makemigrations` and `migrate` to create the new table for the images, you can upload new images which are shown as the available options for the Codered cover image, but you can't save the updated pages because of validation errors.

**Comment by vsalvino** [comment] 2020-07-13 21:49
Closing this as a duplicate of #287. Please continue discussion there!

**Closed by vsalvino** 2020-07-13 21:49 UTC
Labels: Type: Enhancement
