### ISSUE TITLE
[COMMUNITY] Navbar Snippet Select per Site in Layout Settings

### ISSUE THREAD

**Issue by tractcom** [coderedcorp/coderedcms#200] opened 2019-05-28 03:35 UTC
Been playing around with using CodeRed CMS to run multiple sites. So far I cannot see any method of selecting a specific navbar to display, for example:

- If I visit site1.com I would like to display only the navbar1 snippet.
- If I visit site2.com.au I would like to display only the navbar2 snippet.

I can create multiple navbar snippets but the default behaviour seems to display all navbar snippets, no matter which site is being viewed. This becomes an issue when I have a page link:

- If I visit site1.com the page link is correct and I can visit site1.com/page
- If I visit site2.com the page link is incorrect, and it will link to site1.com/page

The temporary solution is to specify external links, but this also prevents the active class on menu items.

The most appropriate solution would be giving an admin user the ability to select a navbar for each site, and only load the selected navbar. The could also be an "All" option if someone still wants the default functionality of loading all navbar snippets.

I am hoping this already exists and I am missing something obvious, otherwise something like the attached mockup (added navbar snippet select) would be an amazing function to have.

![Screenshot from 2019-05-28 13-32-27](https://user-images.githubusercontent.com/13271324/58449052-3bf6b680-814d-11e9-8703-06a1cb295441.png)

**Comment by vsalvino** [comment] 2019-05-28 18:42
Hi Hamish - you are absolutely correct. Technically, this is a bug in coderedcms. In Wagtail, the snippets are tied to a specific site when doing multisite. We are incorrectly rendering them using `.all()`, when instead we should only be pulling the navbars and footers for the specific site.

I will file this as a bug. The issue is here in this template tag: https://github.com/coderedcorp/coderedcms/blob/a3ab4de00e043b22975c06bc5408e9fe2d3a9118/coderedcms/templatetags/coderedcms_tags.py#L82

**Comment by carlosmonari** [comment] 2019-07-01 21:34
Hi there,

Look at:

https://github.com/coderedcorp/coderedcms/issues/202#issuecomment-507006635

i improve a possible solution.

Bye

**Comment by vsalvino** [comment] 2019-08-07 17:08
Closing as duplicate of #202

**Closed by vsalvino** 2019-08-07 17:08 UTC
Labels: Area: Multisite 🏨
