### ISSUE TITLE
Unable to execute runserver

### ISSUE THREAD

**Issue by RubberSeoul** [coderedcorp/coderedcms#652] opened 2024-08-14 07:53 UTC
Following a fresh installation, each attempt to execute runserver results in various errors (see screen dump) the first of which appears to be:
`AttributeError: 'FetchFromCacheMiddleware' object has no attribute '_async_check' `

A couple of notes:
I have followed the steps as outlined here (both pro & basic): https://docs.coderedcorp.com/wagtail-crx/getting_started/install.html
A fresh install of DJango alone works fine
I am new to Python and coderedcms

#### Steps to reproduce
PS> py -m venv venv
PS> powershell -noexit -ExecutionPolicy Bypass -File .\venv\Scripts\activate.ps1
(venv) PS> pip install coderedcms
(venv) PS> coderedcms start "folder name"
(venv) PS> cd "folder name"
(venv) PS> python manage.py migrate
(venv) PS> python manage.py createsuperuser (I used admin with same pw as pc)
(venv) PS> python manage.py runserver

I have deleted the project and virtual folders and restarted several times, each with the same error.

Python 3.11.6
![image](https://github.com/user-attachments/assets/1ae20145-0c62-4dc6-8155-95858f146fba)

**Comment by vsalvino** [comment] 2024-08-14 15:51
This is caused by wagtail-cache https://github.com/coderedcorp/wagtail-cache/issues/74, a fix is in progress.

The solution is to pip install `Django==5.0.*` for now, and pin that in your requirements.txt

**Closed by vsalvino** 2024-08-14 15:51 UTC
Labels: Type: Bug
