### ISSUE TITLE
Upgrade to Wagtail 2.7

### ISSUE THREAD

**Issue by corysutyak** [coderedcorp/coderedcms#267] opened 2019-10-21 15:24 UTC
### Additional context
Normally there isn't a huge issue with upgrading Wagtail versions.  But with 2.7, the admin UI changes significantly which could really conflict with our existing UI overwrites.

**Comment by vsalvino** [comment] 2019-10-21 21:59
I'm hoping we can remove a good portion of our custom `codered-editor.css` and `codered-admin.css`.

There are a few custom things in there that come to mind, that we will want to **keep**:
* Improved UI and colors for draftail editor (it blends in nicer and matches other input boxes, versus having a big black bar and custom fonts)
* Powered by CodeRed bar beneath user name
* Advanced settings toggle button in blocks
* We have some heavy customization to the settings pull-out menu to allow it to display long list of settings, by default it is pretty broken in wagtail once you start adding a bunch of settings.
* Use system font in wagtail admin, versus Open Sans (which doesn't really match anyone's branding, ours, wagtail's, or the client's - why pull in those extra resources on every request for nothing).
* Improve contrast of text and inputs (which might not be relevant anymore since they added a bunch of accessibility improvements in wagtail 2.6)
* Specifically used for the classifiers panel in the page model, there is a UI to call out new features.

I think everything else was related to condensing and nesting the streamfields, and making the rest of the UI match our changes to the streamfields.

We should also do an internal manual regression test on one of our heavy-hitting client sites (ckff) which I think uses every feature of coderedcms.

**Comment by FlipperPA** [comment] 2019-10-22 01:36
It seems some of these are pretty good ideas for Wagtail core as well! I'll let you know how things go with code block.

**Comment by o5728492** [comment] 2019-10-22 06:06
Why not reply to the three questions I asked?
This is very important to me.

**Comment by vsalvino** [comment] 2019-10-23 19:18
It looks like Wagtail 2.7 is adding Python 3.8 support. Would like to get our pipeline up and running with 3.8 before we officially sanction Python 3.8 compatibility: https://github.com/microsoft/azure-pipelines-image-generation/issues/1317

**Comment by FlipperPA** [comment] 2019-12-26 22:55
@vsalvino @corysutyak Any idea when 2.7 support might be coming to CodeRed? Let me know if I can help. We didn't run into any issues with WagtailCodeBlock.

**Comment by vsalvino** [comment] 2019-12-27 03:03
Merged to master. Testing of any existing sites with the master branch (0.17.0) would be appreciated before cutting a release! Note there may be additional migrations added before release so please use a disposable database to test.

**Comment by vsalvino** [comment] 2019-12-27 03:04
Merged to master. Testing of any existing sites with the master branch (0.17.0) would be appreciated before cutting a release! Note there may be additional migrations added before release so please use a disposable database to test.

**Closed by vsalvino** 2019-12-27 03:04 UTC
Labels: Type: Enhancement

**Comment by FlipperPA** [comment] 2019-12-27 11:18
@vsalvino You'll have a test against one of my major sites today! :)

**Comment by FlipperPA** [comment] 2019-12-27 22:28
Hey friends, I think this may still need some work.

Below, please see how Wagtail 2.7 appears on the edit screen for a page at work with a nested StreamField. This screen shot contains the following StreamBlock indentation (3 levels):

* Section
    * Headline
    * Body
        * [Add New Sub-Block to Section]
        * Paragraph

![image](https://user-images.githubusercontent.com/68164/71534605-eeeae680-28cd-11ea-80af-7ef01ae61bed.png)

Note how little indentation there is for each sub-block. Compare that to CodeRedCMS, where we have the following StreamBlock indentation (5 levels):

* Responsive Grid Row
    * Full Width
    * Content
        * Column
            * Column Size
            * Content
                * [Add New Sub-Block to Content]
                * Text (not visible on screenshot, but...)

![image](https://user-images.githubusercontent.com/68164/71534570-bcd98480-28cd-11ea-908c-cc0131087b69.png)

See how this is still including very significant indentation, push sub-blocks to the right? I've made sure to hard refresh in case this was stale CSS assets, but no luck. It looks like the `Content` field is forcing a significant indentation.

Thanks for your efforts, I won't have time to look at this within the next few days, unfortunately; in the middle of a major site launch!

**Comment by FlipperPA** [comment] 2019-12-27 22:31
(submitting as new issue, since this is closed - sorry about that!)
